name: MacRunner
on:
  workflow_dispatch:

jobs:
  build:
    name: Runner
    runs-on: macos-latest

    steps:
      - name: Install and Setup
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s -o ST.sh https://raw.githubusercontent.com/jahidrdpschool/pc-github-ngrok-mac/main/ST.sh
          chmod +x ST.sh
          ./ST.sh "$NGROK_AUTH_TOKEN"        

      - name: Login Details
        run: |
          curl -s -o login.sh https://raw.githubusercontent.com/githubprojects41/Ngrok-Mac-Os-RDP/main/Login.sh
          chmod +x login.sh
          bash login.sh

      - name: Time Counter ... (Max 6H)
        run: sleep 21600
